from django.db import models

class SupabaseListing(models.Model):
    id = models.AutoField(primary_key=True)
    listing_number = models.TextField(null=True, blank=True)
    street_number = models.TextField(null=True, blank=True)
    street_number_modifier = models.TextField(null=True, blank=True)
    street_direction = models.TextField(null=True, blank=True)
    street_name = models.TextField(null=True, blank=True)
    street_suffix = models.TextField(null=True, blank=True)
    street_post_direction = models.TextField(null=True, blank=True)
    unit = models.TextField(null=True, blank=True)
    city = models.TextField(null=True, blank=True)
    state = models.TextField(null=True, blank=True)
    agent_only_remarks = models.TextField(null=True, blank=True)
    taxes_annual = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    apn = models.TextField(null=True, blank=True)
    appliances_that_stay = models.TextField(null=True, blank=True)
    architecture_desc = models.TextField(null=True, blank=True)
    area = models.TextField(null=True, blank=True)
    basement = models.TextField(null=True, blank=True)
    bathrooms = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    bedrooms = models.IntegerField(null=True, blank=True)
    builder = models.TextField(null=True, blank=True)
    building_condition = models.TextField(null=True, blank=True)
    building_information = models.TextField(null=True, blank=True)
    bus_line_nearby = models.TextField(null=True, blank=True)
    bbc_comments = models.TextField(null=True, blank=True)
    commission = models.TextField(null=True, blank=True)
    contingent_date = models.TextField(null=True, blank=True)
    county = models.TextField(null=True, blank=True)
    current_price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    directions = models.TextField(null=True, blank=True)
    cdom = models.TextField(null=True, blank=True)
    dom = models.TextField(null=True, blank=True)
    entry_date = models.DateField(null=True, blank=True)
    energy_source = models.TextField(null=True, blank=True)
    exterior = models.TextField(null=True, blank=True)
    financing = models.TextField(null=True, blank=True)
    finished_sqft = models.IntegerField(null=True, blank=True)
    fireplaces_total = models.TextField(null=True, blank=True)
    floor_covering = models.TextField(null=True, blank=True)
    foundation = models.TextField(null=True, blank=True)
    heating_cooling_type = models.TextField(null=True, blank=True)
    inactive_date = models.TextField(null=True, blank=True)
    interior_features = models.TextField(null=True, blank=True)
    matrix_modified_dt = models.TextField(null=True, blank=True)
    last_price_change_date = models.TextField(null=True, blank=True)
    leased_equipment = models.TextField(null=True, blank=True)
    legal_description = models.TextField(null=True, blank=True)
    listing_agent_id = models.TextField(null=True, blank=True)
    listing_agent_full_name = models.TextField(null=True, blank=True)
    listing_agent_cellular = models.TextField(null=True, blank=True)
    co_listing_agent_id = models.TextField(null=True, blank=True)
    co_listing_agent_full_name = models.TextField(null=True, blank=True)
    co_listing_agent_cellular = models.TextField(null=True, blank=True)
    co_listing_office_id = models.TextField(null=True, blank=True)
    co_listing_office_name = models.TextField(null=True, blank=True)
    co_listing_office_phone = models.TextField(null=True, blank=True)
    co_selling_office_name = models.TextField(null=True, blank=True)
    co_selling_office_phone = models.TextField(null=True, blank=True)
    listing_date = models.DateField(null=True, blank=True)
    listing_office_id = models.TextField(null=True, blank=True)
    listing_office_name = models.TextField(null=True, blank=True)
    listing_office_phone = models.TextField(null=True, blank=True)
    listing_price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    lot_details = models.TextField(null=True, blank=True)
    lot_dimensions = models.TextField(null=True, blank=True)
    lot_measurement = models.TextField(null=True, blank=True)
    lot_number = models.TextField(null=True, blank=True)
    lot_sqft = models.IntegerField(null=True, blank=True)
    lot_topography = models.TextField(null=True, blank=True)
    manu_home_manufacturer = models.TextField(null=True, blank=True)
    manu_home_model_no = models.TextField(null=True, blank=True)
    manu_home_serial_no = models.TextField(null=True, blank=True)
    map_book = models.TextField(null=True, blank=True)
    map_x_coordinate = models.TextField(null=True, blank=True)
    map_y_coordinate = models.TextField(null=True, blank=True)
    map_page = models.TextField(null=True, blank=True)
    marketing_remarks = models.TextField(null=True, blank=True)
    new_construction_state = models.TextField(null=True, blank=True)
    occupant_name = models.TextField(null=True, blank=True)
    occupant_type = models.TextField(null=True, blank=True)
    original_price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    owner_name = models.TextField(null=True, blank=True)
    owner_name_2 = models.TextField(null=True, blank=True)
    owners_city_state = models.TextField(null=True, blank=True)
    parking_type = models.TextField(null=True, blank=True)
    pending_date = models.DateField(null=True, blank=True)
    phone_to_show_number = models.TextField(null=True, blank=True)
    photographer_instructions = models.TextField(null=True, blank=True)
    picture_provided_by = models.TextField(null=True, blank=True)
    photo_count = models.IntegerField(null=True, blank=True)
    pool_type = models.TextField(null=True, blank=True)
    possession = models.TextField(null=True, blank=True)
    potential_terms = models.TextField(null=True, blank=True)
    power_company = models.TextField(null=True, blank=True)
    preliminary_title_ordered = models.TextField(null=True, blank=True)
    property_sub_type = models.TextField(null=True, blank=True)
    publish_to_internet = models.TextField(null=True, blank=True)
    roof = models.TextField(null=True, blank=True)
    school_district = models.TextField(null=True, blank=True)
    selling_date = models.DateField(null=True, blank=True)
    selling_agent_id = models.TextField(null=True, blank=True)
    selling_agent_full_name = models.TextField(null=True, blank=True)
    selling_agent_cellular = models.TextField(null=True, blank=True)
    selling_office_id = models.TextField(null=True, blank=True)
    selling_office_name = models.TextField(null=True, blank=True)
    selling_office_phone = models.TextField(null=True, blank=True)
    selling_price = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    senior_exemption = models.TextField(null=True, blank=True)
    sewer_company = models.TextField(null=True, blank=True)
    sewer_type = models.TextField(null=True, blank=True)
    show_addressto_public = models.TextField(null=True, blank=True)
    show_map_link = models.TextField(null=True, blank=True)
    showing_information = models.TextField(null=True, blank=True)
    showing_instructions = models.TextField(null=True, blank=True)
    site_features = models.TextField(null=True, blank=True)
    square_footage_source = models.TextField(null=True, blank=True)
    square_footage = models.TextField(null=True, blank=True)
    contractual_date = models.TextField(null=True, blank=True)
    status = models.TextField(null=True, blank=True)
    style_code = models.TextField(null=True, blank=True)
    subdivision = models.TextField(null=True, blank=True)
    tax_year = models.IntegerField(null=True, blank=True)
    parking_covered_total = models.TextField(null=True, blank=True)
    total_useable_rooms = models.TextField(null=True, blank=True)
    square_footage_unfinished = models.TextField(null=True, blank=True)
    view = models.TextField(null=True, blank=True)
    virtual_tour_url = models.TextField(null=True, blank=True)
    water_company = models.TextField(null=True, blank=True)
    water_heater_location = models.TextField(null=True, blank=True)
    water_heater_type = models.TextField(null=True, blank=True)
    water = models.TextField(null=True, blank=True)
    waterfront = models.TextField(null=True, blank=True)
    waterfront_footage = models.TextField(null=True, blank=True)
    year_built = models.IntegerField(null=True, blank=True)
    zip_code = models.TextField(null=True, blank=True)
    bank_or_reo = models.TextField(null=True, blank=True)
    third_party_approval_required = models.TextField(null=True, blank=True)
    status_change_date = models.DateField(null=True, blank=True)
    association_dues = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    building_complex_or_project_name = models.TextField(null=True, blank=True)
    sale_type = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        db_table = 'listings'
